{% set name = "libass" %}
{% set version = "0.17.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 78f1179b838d025e9c26e8fef33f8092f65611444ffa1bfc0cfac6a33511a05a

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libass', max_pin='x.x.x') }}
  ignore_run_exports:
    - expat

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - pkg-config
    - libtool
    - nasm
  host:
    - freetype
    - zlib
    - fribidi
    - fontconfig
    - expat
    - libiconv
    - harfbuzz

test:
  commands:
    test -f $PREFIX/lib/libass$SHLIB_EXT

about:
  license: ISC
  license_file: COPYING
  summary: A portable subtitle renderer for the ASS/SSA (Advanced Substation Alpha/Substation Alpha) subtitle format.
  homepage: https://github.com/libass/libass
  repository: https://github.com/libass/libass
  documentation: https://github.com/libass/libass

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - scopatz
